event_homepage:
    path:     /
    defaults: { _controller: EventBundle:Event:index }
    methods:  [GET]
    
event_search:
    path:     /szukaj.html
    defaults: { _controller: EventBundle:Event:index}
    methods:  [POST]

event_addresses:
    path:     /adresy.json
    defaults: { _controller: EventBundle:Event:addresses }


event_add:
    path:     /dodaj.html
    defaults: { _controller: EventBundle:Event:create }

event_view:
    path:     /impreza,{id}.html
    defaults: { _controller: EventBundle:Event:view }
    
event_comment_add:
    path:     /komentuj-impreze,{id}.html
    defaults: { _controller: EventBundle:Event:comment }
    
event_comment_remove:
    path:     /usun-komentarz-imprezy,{id}.html
    defaults: { _controller: EventBundle:Event:commentRemove }